portfolio:
  Therapeutics:
    
    89bio:
      ticker: ETNB
      description: 89bio is a clinical-stage biopharmaceutical company focused on the development and commercialization of innovative therapies for the treatment of liver and cardio-metabolic diseases.
      website: https://www.89bio.com/
      pipeline: https://www.89bio.com/pipeline
      news: https://www.89bio.com/news
      ir: https://ir.89bio.com/
      class: nir-widget--list
      link_class: nir-widget--news--headline
      date_class: nir-widget--news--date-time
      unwrap_link: True
    
    Acumen Pharmaceuticals:
      ticker: ABOS
      description: Acumen Pharmaceuticals is a clinical-stage biopharmaceutical company focused on the development of novel therapeutics for the treatment of Alzheimer's disease and other neurodegenerative diseases.
      website: https://www.acumenpharm.com/
      pipeline: https://www.acumenpharm.com/pipeline
      news: https://www.acumenpharm.com/news
      ir: https://investors.acumenpharm.com/
      class: nir-widget--list
      link_class: nir-widget--news--headline
      date_class: nir-widget--news--date-time
      unwrap_link: True

    Alto Neuroscience:
      ticker: None
      description: Alto Neuroscience is a biotechnology company focused on the development of novel therapeutics for the treatment of neuropsychiatric disorders.
      website: https://www.altoneuroscience.com/
      ir: https://investors.altoneuroscience.com/overview/default.aspx
      class: module_item
      link_class: module_headline
      date_class: module_date-time
      unwrap_link: True

    ASLAN Pharmaceuticals:
      ticker: ASLN
      description: ASLAN Pharmaceuticals is a clinical-stage immunology focused biopharmaceutical company developing innovative treatments to transform the lives of patients.
      website: https://www.aslanpharma.com/
      pipeline: https://www.aslanpharma.com/pipeline
      news: https://www.aslanpharma.com/news
      ir: https://ir.aslanpharma.com/
      class: nirtable
      link_class: nir-widget--news--headline
      date_class: nir-widget--news--date-time
      unwrap_link: True
      
    Corbus Pharmaceuticals:
      ticker: CRBP
      description: Corbus Pharmaceuticals is a clinical-stage biopharmaceutical company focused on the development and commercialization of novel therapeutics to treat rare, chronic, and serious inflammatory and fibrotic diseases.
      website: https://www.corbuspharma.com/
      pipeline: https://www.corbuspharma.com/pipeline
      news: https://www.corbuspharma.com/news
      ir: https://ir.corbuspharma.com/
      class: latest-news
      link_class: single-new
      date_class: date
      unwrap_link: True

    Elevation Oncology:
      ticker: ELEV
      description: Elevation Oncology is a clinical-stage biopharmaceutical company focused on the development of precision medicines for patients with genomically defined cancers.
      website: https://www.elevationoncology.com/
      pipeline: https://www.elevationoncology.com/pipeline
      news: https://www.elevationoncology.com/news
      ir: https://investors.elevationoncology.com/
      class: wd_newsfeed_releases-teaser
      link_class: wd_title
      date_class: wd_date
      unwrap_link: True

    # - Evelo Biosciences:
    #   - ticker: EVLO
    #   - description: Evelo Biosciences is a clinical-stage biotechnology company developing a new modality of orally delivered medicines which act on the small intestinal axis to produce systemic therapeutic effects.
    #   - website: https://www.evelobio.com/
    #   - pipeline: https://www.evelobio.com/pipeline
    #   - news: https://www.evelobio.com/news
    #   - ir: https://ir.evelobio.com/

    Inozyme:
      ticker: INZY
      description: Inozyme Pharma is a rare disease biopharmaceutical company developing novel therapeutics for the treatment of diseases of abnormal mineralization impacting the vasculature, soft tissue, and skeleton.
      website: https://www.inozyme.com/
      pipeline: https://www.inozyme.com/pipeline
      news: https://www.inozyme.com/news
      ir: https://investors.inozyme.com/
      class: nir-widget--list
      link_class: nir-widget--news--headline
      date_class: nir-widget--news--date-time
      unwrap_link: True

    Inspirna:
      ticker: None
      description: Inspirna is a biotechnology company focused on the development of novel therapeutics for the treatment of respiratory diseases.
      website: https://www.inspirna.com/
      ir: https://inspirna.com/news-events/
      class: news-item
      link_class: title
      date_class: $datetime
      unwrap_link: True

    MindMed:
      ticker: MNMD
      description: MindMed is a clinical-stage biopharmaceutical company developing a new generation of medicines for mental health disorders and addiction.
      website: https://www.mindmed.co/
      pipeline: https://www.mindmed.co/pipeline
      news: https://www.mindmed.co/news
      ir: https://ir.mindmed.co/
      class: module-latest-news-all-text
      link_class: media-heading
      date_class: date
      unwrap_link: True


    Molecular Templates:
      ticker: MTEM
      description: Molecular Templates is a clinical-stage biopharmaceutical company focused on the discovery and development of proprietary targeted biologic therapeutics for the treatment of cancer and other serious diseases.
      website: https://www.mtem.com/
      pipeline: https://www.mtem.com/pipeline
      news: https://www.mtem.com/news
      ir: https://www.mtem.com/investors
      class: news-boxes
      link_class: media-heading
      date_class: date
      unwrap_link: True

    Ribon Therapeutics:
      ticker: None
      description: Ribon Therapeutics is a clinical-stage biotechnology company developing first-in-class therapeutics targeting novel enzyme families activated under cellular stress conditions that contribute to disease.
      website: https://www.ribontherapeutics.com/
      pipeline: https://www.ribontherapeutics.com/pipeline
      news: https://www.ribontherapeutics.com/news
      ir: https://ribontx.com/news/
      class: c-content-box
      link_class: c-btn
      date_class: c-title-small
      title_class: c-title-sub

    Tscan Therapeutics:
      ticker: TCRX
      description: Tscan Therapeutics is a biotechnology company focused on the development of novel therapeutics for the treatment of cancer.
      website: https://www.tscan.com/
      pipeline: https://www.tscan.com/pipeline
      news: https://www.tscan.com/news
      ir: https://ir.tscan.com/
      class: nir-widget--list
      link_class: nir-widget--news--headline
      date_class: press-year
      unwrap_link: True
      day_class: press-date

    VBI Vaccines:
      ticker: VBIV
      description: VBI Vaccines is a commercial-stage biopharmaceutical company developing next-generation infectious disease and immuno-oncology vaccines.
      website: https://www.vbivaccines.com/
      pipeline: https://www.vbivaccines.com/pipeline
      news: https://www.vbivaccines.com/news
      ir: https://www.vbivaccines.com/investors/press-releases/
      class: mr-32
      link_class: title
      date_class: date
      unwrap_link: True

    Vedanta Biosciences:
      ticker: None
      description: Vedanta Biosciences is a clinical-stage biopharmaceutical company developing a new category of therapies for immune-mediated diseases based on rationally defined consortia of human microbiome-derived bacteria.
      website: https://www.vedantabio.com/
      pipeline: https://www.vedantabio.com/pipeline
      news: https://www.vedantabio.com/news
      ir: https://www.vedantabio.com/news-media
      class: module--news
      link_class: media-item
      date_class: date
      unwrap_link: True
